crypto-bigint: fix recursion bug in `Rem` impl for `Uint` (#176)
Previously this accidentally recursed instead of calling the inherent
method:

    thread 'uint::div::tests::rem_trait' has overflowed its stack
    fatal runtime error: stack overflow
    error: test failed, to rerun pass `--lib`

This uses UFCS to call the inherent method, and adds a regression test
for all of the possible borrowing patterns for the `Rem` impl on `Uint`.